// Mock window.__TAURI__ and window.tokenLeague for E2E testing
// without the native Tauri binary.
// Injected via Playwright's addInitScript before page scripts load.
//
// Scenario configuration via window.__ATL_E2E_CONFIG__:
//   { desktopAutoInitialized: true, language: "zh-CN", scanDelay: 200 }
// Set BEFORE this script runs (addInitScript runs before page JS).

(function () {
  // ── Scenario config (merge with defaults) ────────────────────
  const cfg = Object.assign({
    desktopAutoInitialized: false,
    language: "en",
    theme: "light",
    scanDelay: 0,          // ms before scan completes (0 = instant)
    emptyData: false,      // true = no usage data (fresh install)
    apiError: false,       // true = checkApi returns error
    largeDataset: 0,       // > 0 = generate N additional usage rows
    syncDelay: 0,
  }, window.__ATL_E2E_CONFIG__ || {});
  window.__ATL_E2E_STATE__ = Object.assign(window.__ATL_E2E_STATE__ || {}, {
    checkApiCount: 0,
    startUsageScanCount: 0,
    startUsageSyncCount: 0,
    checkUpdateCount: 0,
    lastStartUsageScanArgs: null,
  });

  // Use LOCAL dates (same as renderer's localDay()) to avoid timezone mismatch.
  function localDateStr(d) {
    const dd = d instanceof Date ? d : new Date(d);
    const y = dd.getFullYear();
    const m = String(dd.getMonth() + 1).padStart(2, "0");
    const day = String(dd.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
  const now = new Date();
  const today = localDateStr(now);
  const yesterday = localDateStr(new Date(now.getTime() - 86400000));
  const d2 = localDateStr(new Date(now.getTime() - 2 * 86400000));
  const d3 = localDateStr(new Date(now.getTime() - 3 * 86400000));
  const d4 = localDateStr(new Date(now.getTime() - 4 * 86400000));
  const d5 = localDateStr(new Date(now.getTime() - 5 * 86400000));
  const d6 = localDateStr(new Date(now.getTime() - 6 * 86400000));
  const currentHour = now.getHours();

  function readPersistedConfig() {
    try {
      return JSON.parse(window.localStorage.getItem("atl-e2e-config") || "{}");
    } catch {
      return {};
    }
  }

  function persistConfig(config) {
    try {
      window.localStorage.setItem("atl-e2e-config", JSON.stringify(config));
    } catch {
      // localStorage may be unavailable in some harnesses; keep in-memory config.
    }
  }

  // ── Config (matches AppConfig struct) ──────────────────────
  const persistedConfig = readPersistedConfig();
  const mockConfig = Object.assign({
    participantId: "p_test123",
    deviceId: "dev_test456",
    nickname: "Test User",
    nicknameAutoGenerated: false,
    apiBaseUrl: "",
    language: cfg.language,
    theme: cfg.theme,
    showRawTokens: false,
    showEstimatedCost: Boolean(cfg.showEstimatedCost),
    refreshIntervalMinutes: 15,
    launchAtLogin: false,
    hideDockIcon: false,
    desktopAutoInitialized: cfg.desktopAutoInitialized,
    providerRoots: {
      claude_code_local: ["/test-project"],
      codex_local: ["/other-project"],
    },
    providerEnabled: {
      claude_code_local: true,
      codex_local: true,
    },
    cursorDashboardUsage: {},
    localBackup: { enabled: false, directory: "", retentionCount: 7 },
    runtimeLogRetentionDays: 3,
    apiConnection: null,
    syncStatus: null,
    workdirAliases: {},
  }, persistedConfig);

  function clone(value) {
    return JSON.parse(JSON.stringify(value));
  }

  // ── Sync scenario overrides ────────────────────────────────
  if (cfg.syncConfigured) {
    const testApiUrl = "https://test.example.com";
    mockConfig.apiBaseUrl = testApiUrl;
    mockConfig.apiConnection = {
      status: "reachable",
      checkedAt: new Date().toISOString(),
      serverVersion: "1.0.0",
      compatibility: { compatible: true },
    };
    if (cfg.syncConnectionUnchecked) {
      mockConfig.apiConnection = { apiBaseUrl: testApiUrl };
    }
    if (cfg.syncLastStatus || cfg.syncQueuePending) {
      mockConfig.syncStatus = {
        apiBaseUrl: testApiUrl,
        lastAttemptAt: new Date().toISOString(),
        lastFinishedAt: new Date().toISOString(),
        lastSuccessAt: cfg.syncLastStatus === "success" ? new Date().toISOString() : "",
        lastStatus: cfg.syncLastStatus || "",
        lastError: cfg.syncLastError || "",
        lastSuccessSourceFingerprint: cfg.syncLastStatus === "success" ? (cfg.syncLastFingerprint || "mock-fp") : "",
        lastResult: cfg.syncQueuePending ? { queuePending: cfg.syncQueuePending } : null,
      };
    }
    if (cfg.syncCloudUnreachable) {
      mockConfig.apiConnection = {
        status: "error",
        checkedAt: new Date().toISOString(),
        message: "Connection refused",
      };
    }
    if (cfg.syncCloudIncompatible) {
      mockConfig.apiConnection = {
        status: "reachable",
        checkedAt: new Date().toISOString(),
        serverVersion: "0.1.0",
        compatibility: { compatible: false, reason: "version mismatch" },
      };
    }
  }

  // ── Usage items (matches public_usage_item shape) ──────────
  const defaultUsage = [
    {
      day: today, hour: currentHour, toolCode: "claude_code",
      model: "claude-sonnet-4-20250514", providerId: "claude_code_local",
      workdirHash: "abc123", workdirDisplayName: "/test-project",
      inputTokens: 5000, outputTokens: 2000,
      cacheReadTokens: 1000, cacheWriteTokens: 500,
      reasoningTokens: 0, totalTokens: 8500,
    },
    {
      day: yesterday, hour: 14, toolCode: "codex",
      model: "gpt-4o", providerId: "codex_local",
      workdirHash: "def456", workdirDisplayName: "/other-project",
      inputTokens: 3000, outputTokens: 1500,
      cacheReadTokens: 0, cacheWriteTokens: 0,
      reasoningTokens: 0, totalTokens: 4500,
    },
  ];

  // Generate large dataset if configured
  if (cfg.largeDataset > 0 && !cfg.emptyData) {
    const models = ["claude-sonnet-4-20250514", "gpt-4o", "claude-opus-4-20250514", "gpt-4.1"];
    const providers = ["claude_code_local", "codex_local"];
    const workdirs = ["/proj-a", "/proj-b", "/proj-c", "/proj-d", "/proj-e"];
    for (let i = 0; i < cfg.largeDataset; i++) {
      const dayOffset = Math.floor(i / 24); // spread across days
      const d = new Date(now.getTime() - dayOffset * 86400000);
      const h = i % 24;
      const model = models[i % models.length];
      const provider = providers[i % providers.length];
      const wd = workdirs[i % workdirs.length];
      const input = 100 + Math.floor(Math.random() * 2000);
      const output = 50 + Math.floor(Math.random() * 1000);
      defaultUsage.push({
        day: localDateStr(d), hour: h, toolCode: provider === "claude_code_local" ? "claude_code" : "codex",
        model, providerId: provider,
        workdirHash: `wd-${i}`, workdirDisplayName: wd,
        inputTokens: input, outputTokens: output,
        cacheReadTokens: 0, cacheWriteTokens: 0,
        reasoningTokens: 0, totalTokens: input + output,
      });
    }
  }

  const mockUsage = cfg.emptyData ? [] : defaultUsage;

  // ── Health (matches provider_health shape) ─────────────────
  const mockHealth = [
    {
      providerId: "claude_code_local", toolCode: "claude_code",
      enabled: true, detected: true, ok: true, scannedFiles: 3,
      roots: ["/test-project"],
      sources: [{ kind: "auto", id: "/test-project", label: "~/test-project", path: "/test-project", ignored: false }],
    },
    {
      providerId: "codex_local", toolCode: "codex",
      enabled: true, detected: true, ok: true, scannedFiles: 2,
      roots: ["/other-project"],
      sources: [{ kind: "auto", id: "/other-project", label: "~/other-project", path: "/other-project", ignored: false }],
    },
  ];

  // ── Pre-computed aggregates ────────────────────────────────
  function filterByRange(items, range) {
    if (range === "today") return items.filter(u => u.day === today);
    if (/^\d{4}-\d{2}-\d{2}\.\.\d{4}-\d{2}-\d{2}$/.test(range || "")) {
      const [from, to] = range.split("..");
      return items.filter(u => u.day >= from && u.day <= to);
    }
    if (range === "7d") return items.filter(u => {
      const d = new Date(u.day + "T00:00:00");
      const cutoff = new Date(now.getTime() - 7 * 86400000);
      return d >= cutoff;
    });
    // "all" or unknown → return everything
    return items;
  }

  function aggregate(items) {
    return items.reduce((acc, u) => {
      acc.inputTokens += u.inputTokens;
      acc.outputTokens += u.outputTokens;
      acc.cacheReadTokens += u.cacheReadTokens;
      acc.cacheWriteTokens += u.cacheWriteTokens;
      acc.reasoningTokens += u.reasoningTokens;
      acc.totalTokens += u.totalTokens;
      acc.rows += 1;
      return acc;
    }, { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, totalTokens: 0, rows: 0 });
  }

  function makeSummary(range, from, to) {
    const filtered = filterByRange(mockUsage, range);
    const totals = aggregate(filtered);

    // Provider breakdown for filtered items
    const providerMap = {};
    filtered.forEach(u => {
      if (!providerMap[u.providerId]) providerMap[u.providerId] = { name: u.providerId, totalTokens: 0, rows: 0 };
      providerMap[u.providerId].totalTokens += u.totalTokens;
      providerMap[u.providerId].rows += 1;
    });

    // Workdir breakdown
    const workdirMap = {};
    filtered.forEach(u => {
      if (!workdirMap[u.workdirHash]) workdirMap[u.workdirHash] = { name: u.workdirDisplayName, workdirHash: u.workdirHash, totalTokens: 0, rows: 0 };
      workdirMap[u.workdirHash].totalTokens += u.totalTokens;
      workdirMap[u.workdirHash].rows += 1;
    });

    // Model breakdown
    const modelMap = {};
    filtered.forEach(u => {
      if (!modelMap[u.model]) modelMap[u.model] = { name: u.model, totalTokens: 0, rows: 0 };
      modelMap[u.model].totalTokens += u.totalTokens;
      modelMap[u.model].rows += 1;
    });

    return {
      range, from, to,
      totals,
      providers: Object.values(providerMap),
      workdirs: Object.values(workdirMap),
      models: Object.values(modelMap),
    };
  }

  function makeTrend(range, grain) {
    const filtered = filterByRange(mockUsage, range);
    if (range === "today") {
      const bucket = aggregate(filtered);
      return {
        range, grain, from: today, to: today,
        items: [{ bucket: `${today}T${currentHour}`, periodStart: today, periodEnd: today, hour: currentHour, ...bucket }],
      };
    }
    // Group by day for non-today ranges
    const byDay = {};
    filtered.forEach(u => {
      if (!byDay[u.day]) byDay[u.day] = { bucket: u.day, periodStart: u.day, periodEnd: u.day, hour: null, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, totalTokens: 0 };
      byDay[u.day].inputTokens += u.inputTokens;
      byDay[u.day].outputTokens += u.outputTokens;
      byDay[u.day].cacheReadTokens += u.cacheReadTokens;
      byDay[u.day].cacheWriteTokens += u.cacheWriteTokens;
      byDay[u.day].reasoningTokens += u.reasoningTokens;
      byDay[u.day].totalTokens += u.totalTokens;
    });
    const days = [today, yesterday, d2, d3, d4, d5, d6];
    const items = days.filter(d => byDay[d]).map(d => byDay[d]);
    return { range, grain, from: items.length ? items[items.length - 1].periodStart : today, to: today, items };
  }

  function makeWorkdirs(range) {
    const filtered = filterByRange(mockUsage, range);
    const workdirMap = {};
    filtered.forEach(u => {
      if (!workdirMap[u.workdirHash]) workdirMap[u.workdirHash] = { workdirHash: u.workdirHash, name: u.workdirDisplayName, rows: 0, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, totalTokens: 0 };
      const w = workdirMap[u.workdirHash];
      w.inputTokens += u.inputTokens;
      w.outputTokens += u.outputTokens;
      w.cacheReadTokens += u.cacheReadTokens;
      w.cacheWriteTokens += u.cacheWriteTokens;
      w.reasoningTokens += u.reasoningTokens;
      w.totalTokens += u.totalTokens;
      w.rows += 1;
    });
    return { range, from: range === "today" ? today : yesterday, to: today, items: Object.values(workdirMap) };
  }

  const scanSnapshot = {
    items: mockUsage, health: mockHealth, cacheVersion: 3,
    rowCount: mockUsage.length, scannedAt: new Date().toISOString(),
    sourceFingerprint: cfg.syncLocalFingerprint || "mock-fp", usageSourceConfigFingerprint: "mock-ucfp", fromCache: false,
  };

  // ── Scan state machine (simulates running → done) ─────────
  let scanState = { running: false, done: false, snapshot: null };
  let nextTaskId = 1;

  function startScan(force = false, syncAfter = false) {
    const delay = cfg.scanDelay || 0;
    const taskId = `mock-task-${nextTaskId++}`;
    const finishScan = () => {
      if (syncAfter && mockConfig.apiBaseUrl) {
        window.__ATL_E2E_STATE__.startUsageSyncCount += 1;
        scanState = {
          running: false,
          syncRunning: true,
          done: false,
          snapshot: scanSnapshot,
          taskId,
          force,
          phase: "uploading",
          syncResult: null,
          syncError: null,
        };
        const syncDelay = cfg.syncDelay || 0;
        if (syncDelay > 0) setTimeout(() => finishSync(taskId, force), syncDelay);
        else finishSync(taskId, force);
        return;
      }
      scanState = { running: false, syncRunning: false, done: true, snapshot: scanSnapshot, taskId: null, force, phase: null };
    };
    if (delay > 0) {
      scanState = { running: true, syncRunning: false, done: false, snapshot: null, taskId, force, phase: "scanning" };
      setTimeout(finishScan, delay);
    } else {
      finishScan();
    }
  }

  function finishSync(taskId, force = false) {
    const nowIso = new Date().toISOString();
    const result = {
      synced: true,
      accepted: mockUsage.length,
      rejected: 0,
      bucketCount: mockUsage.length,
      uploadedBucketCount: mockUsage.length,
      noopBucketCount: 0,
      queued: false,
      queuePending: 0,
      sourceFingerprint: scanSnapshot.sourceFingerprint,
      scannedAt: scanSnapshot.scannedAt,
    };
    mockConfig.syncStatus = {
      apiBaseUrl: mockConfig.apiBaseUrl,
      lastAttemptAt: nowIso,
      lastFinishedAt: nowIso,
      lastSuccessAt: nowIso,
      lastStatus: "success",
      lastError: "",
      lastSuccessSourceFingerprint: scanSnapshot.sourceFingerprint,
      lastResult: result,
    };
    mockConfig.lastSyncAt = nowIso;
    mockConfig.lastSyncStatus = "success";
    mockConfig.lastSyncApiBaseUrl = mockConfig.apiBaseUrl;
    mockConfig.lastSyncError = "";
    scanState = {
      running: false,
      syncRunning: false,
      done: true,
      snapshot: scanSnapshot,
      taskId: null,
      force,
      phase: null,
      syncResult: result,
      syncError: null,
    };
  }

  function startSync(force = false) {
    window.__ATL_E2E_STATE__.startUsageSyncCount += 1;
    const taskId = `mock-sync-${nextTaskId++}`;
    scanState = {
      running: false,
      syncRunning: true,
      started: true,
      snapshot: null,
      taskId,
      force,
      phase: "uploading",
      syncResult: null,
      syncError: null,
    };
    const delay = cfg.syncDelay || 0;
    if (delay > 0) setTimeout(() => finishSync(taskId, force), delay);
    else finishSync(taskId, force);
    return { ...scanState, started: true, syncRunning: delay > 0, phase: delay > 0 ? "uploading" : null };
  }

  // Start a scan immediately so data is available on boot
  startScan(false);

  // ── Tauri bridge ───────────────────────────────────────────
  window.__TAURI__ = {
    core: {
      invoke: (command) => {
        if (command === "platform") return Promise.resolve("darwin");
        return Promise.resolve(null);
      },
    },
    event: { listen: () => Promise.resolve(() => {}) },
  };

  function applyOverrides(api) {
    api.getConfig = () => Promise.resolve(clone(mockConfig));
    api.checkApi = () => {
      window.__ATL_E2E_STATE__.checkApiCount += 1;
      return (cfg.apiError || cfg.syncCloudUnreachable)
        ? Promise.resolve({ status: "error", checkedAt: new Date().toISOString(), message: "Connection refused" })
        : cfg.syncCloudIncompatible
          ? Promise.resolve({ status: "reachable", checkedAt: new Date().toISOString(), serverVersion: "0.1.0", compatibility: { compatible: false, reason: "version mismatch" } })
        : Promise.resolve({ status: "reachable", checkedAt: new Date().toISOString(), serverVersion: "1.0.0", compatibility: { compatible: true } });
    };
    api.providerHealth = () => Promise.resolve(mockHealth);
    api.brandLogo = () => {
      if (window.__ATL_E2E_STATE__.brandLogoError || cfg.brandLogoError) {
        return Promise.reject(new Error("Brand logo failed"));
      }
      return Promise.resolve({
        dataUrl: cfg.brandLogoDataUrl || null,
        logoUrl: cfg.brandLogoUrl || null,
        byteLength: cfg.brandLogoDataUrl ? cfg.brandLogoDataUrl.length : 0,
        contentType: cfg.brandLogoContentType || "image/png",
      });
    };
    api.modelPrices = () => Promise.resolve(cfg.modelPrices || { custom: [], openrouter: [], aliases: [] });
    api.appVersion = () => Promise.resolve("0.7.0-test");
    api.getMyIdentity = () => Promise.resolve({ deviceId: "dev_test456", nickname: "Test User", identityMode: "named" });
    api.backgroundStatus = () => Promise.resolve({ running: false });
    api.fullReconcileStatus = () => Promise.resolve({ status: "idle", running: false });
    api.diagnosticsStatus = () => Promise.resolve({ runtimeLogPath: "/tmp/test.log" });
    api.localBackupStatus = () => Promise.resolve({ enabled: false });
    api.enforcementStatus = () => Promise.resolve({ mandatory: false });

    api.scanUsage = () => Promise.resolve({ added: mockUsage.length });
    api.startUsageScan = (args) => {
      window.__ATL_E2E_STATE__.startUsageScanCount += 1;
      window.__ATL_E2E_STATE__.lastStartUsageScanArgs = clone(args || {});
      // Real sidecar returns existing status if already running
      if (scanState.running || scanState.syncRunning) return Promise.resolve(scanState);
      startScan(Boolean(args?.force), Boolean(args?.syncAfter));
      return Promise.resolve(scanState);
    };
    api.usageScanStatus = () => Promise.resolve(scanState);

    api.usageSummary = (args) => {
      const range = args?.range || "today";
      return Promise.resolve(makeSummary(range, range === "today" ? today : range === "all" ? "" : yesterday, today));
    };

    api.usageTrend = (args) => {
      const range = args?.range || "today";
      const grain = range === "today" ? "hour" : "day";
      return Promise.resolve(makeTrend(range, grain));
    };

    api.usageWorkdirs = (args) => {
      const range = args?.range || "today";
      return Promise.resolve(makeWorkdirs(range));
    };

    api.syncUsage = () => cfg.apiError
      ? Promise.reject(new Error("Network error"))
      : Promise.resolve(startSync(false));
    api.startUsageSync = () => Promise.resolve(startSync(false));

    api.initConfig = (args) => {
      Object.assign(mockConfig, args?.input || args || {});
      persistConfig(mockConfig);
      return Promise.resolve(clone(mockConfig));
    };
    api.updateConfig = (args) => {
      Object.assign(mockConfig, args?.input || args || {});
      persistConfig(mockConfig);
      return Promise.resolve(clone(mockConfig));
    };
    api.logEvent = () => Promise.resolve(null);
    api.rebuildTrayMenu = () => Promise.resolve(null);
    api.updateTrayCost = () => Promise.resolve(null);
    api.resetLocalData = () => Promise.resolve(null);

    // Provider roots
    api.addProviderRoot = () => Promise.resolve(clone(mockConfig));
    api.removeProviderRoot = () => Promise.resolve(clone(mockConfig));

    // Workdir alias
    api.setWorkdirAlias = (workdirHash, alias) => {
      if (!mockConfig.workdirAliases) mockConfig.workdirAliases = {};
      const key = String(workdirHash || "");
      const value = String(alias || "").trim();
      if (key && value) {
        mockConfig.workdirAliases[key] = value;
      } else if (key) {
        delete mockConfig.workdirAliases[key];
      }
      persistConfig(mockConfig);
      return Promise.resolve(clone(mockConfig));
    };

    // Cursor
    api.startCursorConnect = () => Promise.resolve({ url: "https://mock-cursor-oauth.test", state: "pending" });
    api.pollCursorConnect = () => Promise.resolve({ state: "pending" });
    api.cancelCursorConnect = () => Promise.resolve(null);
    api.removeCursorToken = () => Promise.resolve(null);
    api.disconnectCursor = () => Promise.resolve(null);

    // Auto-source
    api.ignoreAutoSource = () => Promise.resolve(null);
    api.unignoreAutoSource = () => Promise.resolve(null);

    // Diagnostics
    api.clearRuntimeLog = () => Promise.resolve(null);
    api.revealRuntimeLogDirectory = () => Promise.resolve(null);
    api.exportDiagnostics = () => Promise.resolve(null);

    // Backup
    api.localBackupStatus = () => Promise.resolve({ enabled: false });
    api.createLocalBackup = () => Promise.resolve({ ok: true, path: "/tmp/backup.json" });
    api.restoreLocalBackup = () => Promise.resolve({ ok: true });
    api.clearLocalBackups = () => Promise.resolve(null);
    api.chooseBackupDirectory = () => Promise.resolve({ path: "/tmp/backups" });
    api.pickLocalBackup = () => Promise.resolve({ path: "/tmp/backup.json" });
    api.restoreLocalBackupFile = () => Promise.resolve({ ok: true });

    // Updates
    api.checkUpdate = () => {
      window.__ATL_E2E_STATE__.checkUpdateCount += 1;
      return Promise.resolve(null);
    };
    api.downloadUpdate = () => Promise.resolve(null);
    api.installAndRestartUpdate = () => Promise.resolve(null);
    api.downloadInstaller = () => Promise.resolve(null);

    // Reset
    api.resetWithCloud = () => Promise.resolve(null);

    // Export/Import
    api.exportIdentity = () => Promise.resolve(null);
    api.exportConfig = () => Promise.resolve(null);
    api.importIdentity = () => Promise.resolve(null);
    api.importConfig = () => Promise.resolve(null);

    // Usage detail
    api.usageDetailPage = () => Promise.resolve({ items: [], totalRows: 0 });
    api.usageDetailWindow = () => Promise.resolve({ items: [], totalRows: 0 });
    api.saveShareImage = (input) => {
      window.__ATL_E2E_STATE__.lastShareImageSave = clone(input || {});
      return Promise.resolve({ canceled: false, filePath: "/tmp/ai-token-league-share.png" });
    };
  }

  let _tokenLeague;
  Object.defineProperty(window, "tokenLeague", {
    get() { return _tokenLeague; },
    set(value) { _tokenLeague = value; applyOverrides(_tokenLeague); },
    configurable: true,
    enumerable: true,
  });
})();
