// Mock window.__TAURI__ and window.tokenLeague for E2E testing
// without the native Tauri binary.
// Injected via Playwright's addInitScript before page scripts load.
//
// Scenario configuration via window.__ATL_E2E_CONFIG__:
//   { desktopAutoInitialized: true, language: "zh-CN", scanDelay: 200 }
// Set BEFORE this script runs (addInitScript runs before page JS).

(function () {
  // ── Scenario config (merge with defaults) ────────────────────
  const cfg = Object.assign({
    desktopAutoInitialized: false,
    language: "en",
    scanDelay: 0,          // ms before scan completes (0 = instant)
    emptyData: false,      // true = no usage data (fresh install)
    apiError: false,       // true = checkApi returns error
    largeDataset: 0,       // > 0 = generate N additional usage rows
  }, window.__ATL_E2E_CONFIG__ || {});

  // Use LOCAL dates (same as renderer's localDay()) to avoid timezone mismatch.
  function localDateStr(d) {
    const dd = d instanceof Date ? d : new Date(d);
    const y = dd.getFullYear();
    const m = String(dd.getMonth() + 1).padStart(2, "0");
    const day = String(dd.getDate()).padStart(2, "0");
    return `${y}-${m}-${day}`;
  }
  const now = new Date();
  const today = localDateStr(now);
  const yesterday = localDateStr(new Date(now.getTime() - 86400000));
  const d2 = localDateStr(new Date(now.getTime() - 2 * 86400000));
  const d3 = localDateStr(new Date(now.getTime() - 3 * 86400000));
  const d4 = localDateStr(new Date(now.getTime() - 4 * 86400000));
  const d5 = localDateStr(new Date(now.getTime() - 5 * 86400000));
  const d6 = localDateStr(new Date(now.getTime() - 6 * 86400000));
  const currentHour = now.getHours();

  // ── Config (matches AppConfig struct) ──────────────────────
  const mockConfig = {
    participantId: "p_test123",
    deviceId: "dev_test456",
    nickname: "Test User",
    nicknameAutoGenerated: false,
    apiBaseUrl: "",
    language: cfg.language,
    showRawTokens: false,
    showEstimatedCost: false,
    refreshIntervalMinutes: 15,
    launchAtLogin: false,
    hideDockIcon: false,
    desktopAutoInitialized: cfg.desktopAutoInitialized,
    providerRoots: {
      claude_code_local: ["/test-project"],
      codex_local: ["/other-project"],
    },
    providerEnabled: {
      claude_code_local: true,
      codex_local: true,
    },
    cursorDashboardUsage: {},
    localBackup: { enabled: false, directory: "", retentionCount: 7 },
    runtimeLogRetentionDays: 3,
    apiConnection: null,
    syncStatus: null,
    workdirAliases: {},
  };

  // ── Usage items (matches public_usage_item shape) ──────────
  const defaultUsage = [
    {
      day: today, hour: currentHour, toolCode: "claude_code",
      model: "claude-sonnet-4-20250514", providerId: "claude_code_local",
      workdirHash: "abc123", workdirDisplayName: "/test-project",
      inputTokens: 5000, outputTokens: 2000,
      cacheReadTokens: 1000, cacheWriteTokens: 500,
      reasoningTokens: 0, totalTokens: 8500,
    },
    {
      day: yesterday, hour: 14, toolCode: "codex",
      model: "gpt-4o", providerId: "codex_local",
      workdirHash: "def456", workdirDisplayName: "/other-project",
      inputTokens: 3000, outputTokens: 1500,
      cacheReadTokens: 0, cacheWriteTokens: 0,
      reasoningTokens: 0, totalTokens: 4500,
    },
  ];

  // Generate large dataset if configured
  if (cfg.largeDataset > 0 && !cfg.emptyData) {
    const models = ["claude-sonnet-4-20250514", "gpt-4o", "claude-opus-4-20250514", "gpt-4.1"];
    const providers = ["claude_code_local", "codex_local"];
    const workdirs = ["/proj-a", "/proj-b", "/proj-c", "/proj-d", "/proj-e"];
    for (let i = 0; i < cfg.largeDataset; i++) {
      const dayOffset = Math.floor(i / 24); // spread across days
      const d = new Date(now.getTime() - dayOffset * 86400000);
      const h = i % 24;
      const model = models[i % models.length];
      const provider = providers[i % providers.length];
      const wd = workdirs[i % workdirs.length];
      const input = 100 + Math.floor(Math.random() * 2000);
      const output = 50 + Math.floor(Math.random() * 1000);
      defaultUsage.push({
        day: localDateStr(d), hour: h, toolCode: provider === "claude_code_local" ? "claude_code" : "codex",
        model, providerId: provider,
        workdirHash: `wd-${i}`, workdirDisplayName: wd,
        inputTokens: input, outputTokens: output,
        cacheReadTokens: 0, cacheWriteTokens: 0,
        reasoningTokens: 0, totalTokens: input + output,
      });
    }
  }

  const mockUsage = cfg.emptyData ? [] : defaultUsage;

  // ── Health (matches provider_health shape) ─────────────────
  const mockHealth = [
    {
      providerId: "claude_code_local", toolCode: "claude_code",
      enabled: true, detected: true, ok: true, scannedFiles: 3,
      roots: ["/test-project"],
      sources: [{ kind: "auto", id: "/test-project", label: "~/test-project", path: "/test-project", ignored: false }],
    },
    {
      providerId: "codex_local", toolCode: "codex",
      enabled: true, detected: true, ok: true, scannedFiles: 2,
      roots: ["/other-project"],
      sources: [{ kind: "auto", id: "/other-project", label: "~/other-project", path: "/other-project", ignored: false }],
    },
  ];

  // ── Pre-computed aggregates ────────────────────────────────
  function filterByRange(items, range) {
    if (range === "today") return items.filter(u => u.day === today);
    if (range === "7d") return items.filter(u => {
      const d = new Date(u.day + "T00:00:00");
      const cutoff = new Date(now.getTime() - 7 * 86400000);
      return d >= cutoff;
    });
    // "all" or unknown → return everything
    return items;
  }

  function aggregate(items) {
    return items.reduce((acc, u) => {
      acc.inputTokens += u.inputTokens;
      acc.outputTokens += u.outputTokens;
      acc.cacheReadTokens += u.cacheReadTokens;
      acc.cacheWriteTokens += u.cacheWriteTokens;
      acc.reasoningTokens += u.reasoningTokens;
      acc.totalTokens += u.totalTokens;
      acc.rows += 1;
      return acc;
    }, { inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, totalTokens: 0, rows: 0 });
  }

  function makeSummary(range, from, to) {
    const filtered = filterByRange(mockUsage, range);
    const totals = aggregate(filtered);

    // Provider breakdown for filtered items
    const providerMap = {};
    filtered.forEach(u => {
      if (!providerMap[u.providerId]) providerMap[u.providerId] = { name: u.providerId, totalTokens: 0, rows: 0 };
      providerMap[u.providerId].totalTokens += u.totalTokens;
      providerMap[u.providerId].rows += 1;
    });

    // Workdir breakdown
    const workdirMap = {};
    filtered.forEach(u => {
      if (!workdirMap[u.workdirHash]) workdirMap[u.workdirHash] = { name: u.workdirDisplayName, workdirHash: u.workdirHash, totalTokens: 0, rows: 0 };
      workdirMap[u.workdirHash].totalTokens += u.totalTokens;
      workdirMap[u.workdirHash].rows += 1;
    });

    // Model breakdown
    const modelMap = {};
    filtered.forEach(u => {
      if (!modelMap[u.model]) modelMap[u.model] = { name: u.model, totalTokens: 0, rows: 0 };
      modelMap[u.model].totalTokens += u.totalTokens;
      modelMap[u.model].rows += 1;
    });

    return {
      range, from, to,
      totals,
      providers: Object.values(providerMap),
      workdirs: Object.values(workdirMap),
      models: Object.values(modelMap),
    };
  }

  function makeTrend(range, grain) {
    const filtered = filterByRange(mockUsage, range);
    if (range === "today") {
      const bucket = aggregate(filtered);
      return {
        range, grain, from: today, to: today,
        items: [{ bucket: `${today}T${currentHour}`, periodStart: today, periodEnd: today, hour: currentHour, ...bucket }],
      };
    }
    // Group by day for non-today ranges
    const byDay = {};
    filtered.forEach(u => {
      if (!byDay[u.day]) byDay[u.day] = { bucket: u.day, periodStart: u.day, periodEnd: u.day, hour: null, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, totalTokens: 0 };
      byDay[u.day].inputTokens += u.inputTokens;
      byDay[u.day].outputTokens += u.outputTokens;
      byDay[u.day].cacheReadTokens += u.cacheReadTokens;
      byDay[u.day].cacheWriteTokens += u.cacheWriteTokens;
      byDay[u.day].reasoningTokens += u.reasoningTokens;
      byDay[u.day].totalTokens += u.totalTokens;
    });
    const days = [today, yesterday, d2, d3, d4, d5, d6];
    const items = days.filter(d => byDay[d]).map(d => byDay[d]);
    return { range, grain, from: items.length ? items[items.length - 1].periodStart : today, to: today, items };
  }

  function makeWorkdirs(range) {
    const filtered = filterByRange(mockUsage, range);
    const workdirMap = {};
    filtered.forEach(u => {
      if (!workdirMap[u.workdirHash]) workdirMap[u.workdirHash] = { workdirHash: u.workdirHash, name: u.workdirDisplayName, rows: 0, inputTokens: 0, outputTokens: 0, cacheReadTokens: 0, cacheWriteTokens: 0, reasoningTokens: 0, totalTokens: 0 };
      const w = workdirMap[u.workdirHash];
      w.inputTokens += u.inputTokens;
      w.outputTokens += u.outputTokens;
      w.cacheReadTokens += u.cacheReadTokens;
      w.cacheWriteTokens += u.cacheWriteTokens;
      w.reasoningTokens += u.reasoningTokens;
      w.totalTokens += u.totalTokens;
      w.rows += 1;
    });
    return { range, from: range === "today" ? today : yesterday, to: today, items: Object.values(workdirMap) };
  }

  const scanSnapshot = {
    items: mockUsage, health: mockHealth, cacheVersion: 3,
    rowCount: mockUsage.length, scannedAt: new Date().toISOString(),
    sourceFingerprint: "mock-fp", usageSourceConfigFingerprint: "mock-ucfp", fromCache: false,
  };

  // ── Scan state machine (simulates running → done) ─────────
  let scanState = { running: false, done: false, snapshot: null };

  function startScan() {
    const delay = cfg.scanDelay || 0;
    if (delay > 0) {
      scanState = { running: true, done: false, snapshot: null, taskId: "mock-task-1" };
      setTimeout(() => {
        scanState = { running: false, done: true, snapshot: scanSnapshot, taskId: null };
      }, delay);
    } else {
      scanState = { running: false, done: true, snapshot: scanSnapshot, taskId: null };
    }
  }

  // Start a scan immediately so data is available on boot
  startScan();

  // ── Tauri bridge ───────────────────────────────────────────
  window.__TAURI__ = {
    core: {
      invoke: (command) => {
        if (command === "platform") return Promise.resolve("darwin");
        return Promise.resolve(null);
      },
    },
    event: { listen: () => Promise.resolve(() => {}) },
  };

  function applyOverrides(api) {
    api.getConfig = () => Promise.resolve(mockConfig);
    api.checkApi = () => cfg.apiError
      ? Promise.resolve({ status: "error", message: "Connection refused" })
      : Promise.resolve({ status: "ok" });
    api.providerHealth = () => Promise.resolve(mockHealth);
    api.modelPrices = () => Promise.resolve({ custom: [], openrouter: [], aliases: [] });
    api.appVersion = () => Promise.resolve("0.7.0-test");
    api.getMyIdentity = () => Promise.resolve({ deviceId: "dev_test456", nickname: "Test User", identityMode: "named" });
    api.backgroundStatus = () => Promise.resolve({ running: false });
    api.diagnosticsStatus = () => Promise.resolve({ runtimeLogPath: "/tmp/test.log" });
    api.localBackupStatus = () => Promise.resolve({ enabled: false });
    api.enforcementStatus = () => Promise.resolve({ mandatory: false });

    api.scanUsage = () => Promise.resolve({ added: mockUsage.length });
    api.startUsageScan = () => {
      // Real sidecar returns existing status if already running
      if (scanState.running) return Promise.resolve(scanState);
      startScan();
      return Promise.resolve(scanState);
    };
    api.usageScanStatus = () => Promise.resolve(scanState);

    api.usageSummary = (args) => {
      const range = args?.range || "today";
      return Promise.resolve(makeSummary(range, range === "today" ? today : range === "all" ? "" : yesterday, today));
    };

    api.usageTrend = (args) => {
      const range = args?.range || "today";
      const grain = range === "today" ? "hour" : "day";
      return Promise.resolve(makeTrend(range, grain));
    };

    api.usageWorkdirs = (args) => {
      const range = args?.range || "today";
      return Promise.resolve(makeWorkdirs(range));
    };

    api.syncUsage = () => cfg.apiError
      ? Promise.reject(new Error("Network error"))
      : Promise.resolve({ synced: true });
    api.startUsageSync = () => Promise.resolve({ started: true });

    api.initConfig = (args) => {
      Object.assign(mockConfig, args?.input || args || {});
      return Promise.resolve(mockConfig);
    };
    api.updateConfig = (args) => {
      Object.assign(mockConfig, args?.input || args || {});
      return Promise.resolve(mockConfig);
    };
    api.logEvent = () => Promise.resolve(null);
    api.rebuildTrayMenu = () => Promise.resolve(null);
    api.updateTrayCost = () => Promise.resolve(null);
    api.resetLocalData = () => Promise.resolve(null);

    // Provider roots
    api.addProviderRoot = () => Promise.resolve(mockConfig);
    api.removeProviderRoot = () => Promise.resolve(mockConfig);

    // Workdir alias
    api.setWorkdirAlias = () => Promise.resolve(null);

    // Cursor
    api.startCursorConnect = () => Promise.resolve({ url: "https://mock-cursor-oauth.test", state: "pending" });
    api.pollCursorConnect = () => Promise.resolve({ state: "pending" });
    api.cancelCursorConnect = () => Promise.resolve(null);
    api.removeCursorToken = () => Promise.resolve(null);
    api.disconnectCursor = () => Promise.resolve(null);

    // Auto-source
    api.ignoreAutoSource = () => Promise.resolve(null);
    api.unignoreAutoSource = () => Promise.resolve(null);

    // Diagnostics
    api.clearRuntimeLog = () => Promise.resolve(null);
    api.revealRuntimeLogDirectory = () => Promise.resolve(null);
    api.exportDiagnostics = () => Promise.resolve(null);

    // Backup
    api.localBackupStatus = () => Promise.resolve({ enabled: false });
    api.createLocalBackup = () => Promise.resolve({ ok: true, path: "/tmp/backup.json" });
    api.restoreLocalBackup = () => Promise.resolve({ ok: true });
    api.clearLocalBackups = () => Promise.resolve(null);
    api.chooseBackupDirectory = () => Promise.resolve({ path: "/tmp/backups" });
    api.pickLocalBackup = () => Promise.resolve({ path: "/tmp/backup.json" });
    api.restoreLocalBackupFile = () => Promise.resolve({ ok: true });

    // Updates
    api.checkUpdate = () => Promise.resolve(null);
    api.downloadUpdate = () => Promise.resolve(null);
    api.installAndRestartUpdate = () => Promise.resolve(null);
    api.downloadInstaller = () => Promise.resolve(null);

    // Reset
    api.resetWithCloud = () => Promise.resolve(null);

    // Export/Import
    api.exportIdentity = () => Promise.resolve(null);
    api.exportConfig = () => Promise.resolve(null);
    api.importIdentity = () => Promise.resolve(null);
    api.importConfig = () => Promise.resolve(null);

    // Usage detail
    api.usageDetailPage = () => Promise.resolve({ items: [], totalRows: 0 });
    api.usageDetailWindow = () => Promise.resolve({ items: [], totalRows: 0 });
  }

  let _tokenLeague;
  Object.defineProperty(window, "tokenLeague", {
    get() { return _tokenLeague; },
    set(value) { _tokenLeague = value; applyOverrides(_tokenLeague); },
    configurable: true,
    enumerable: true,
  });
})();
