-- 002: Add hourly fact table (方案 C: separate hourly table + daily serving table)

CREATE TABLE IF NOT EXISTS usage_hourly (
  usageKey VARCHAR(512) PRIMARY KEY,
  day DATE NOT NULL,
  hour TINYINT NOT NULL,
  participantId VARCHAR(96) NOT NULL,
  deviceId VARCHAR(96) NOT NULL,
  toolCode VARCHAR(96) NOT NULL,
  providerId VARCHAR(96) NOT NULL,
  workdirId VARCHAR(180) NOT NULL,
  workdirHash VARCHAR(128) NOT NULL,
  workdirDisplayName VARCHAR(255) NOT NULL,
  model VARCHAR(190) NOT NULL,
  inputTokens BIGINT NOT NULL DEFAULT 0,
  outputTokens BIGINT NOT NULL DEFAULT 0,
  cacheReadTokens BIGINT NOT NULL DEFAULT 0,
  cacheWriteTokens BIGINT NOT NULL DEFAULT 0,
  reasoningTokens BIGINT NOT NULL DEFAULT 0,
  totalTokens BIGINT NOT NULL DEFAULT 0,
  estimatedCostUsd DECIMAL(18,8) NULL,
  costQuality VARCHAR(32) NOT NULL DEFAULT '',
  pricingVersion VARCHAR(128) NOT NULL DEFAULT '',
  pricingModel VARCHAR(190) NOT NULL DEFAULT '',
  pricingSource VARCHAR(64) NOT NULL DEFAULT '',
  sourceQuality VARCHAR(32) NOT NULL DEFAULT 'unknown',
  rawSourceRef VARCHAR(255) NOT NULL DEFAULT '',
  providerVersion VARCHAR(64) NOT NULL DEFAULT '',
  parserVersion VARCHAR(64) NOT NULL DEFAULT '',
  sourceFingerprint VARCHAR(128) NOT NULL DEFAULT '',
  uploadedAt VARCHAR(40) NULL,
  INDEX idx_hourly_day_tokens (day, totalTokens),
  INDEX idx_hourly_participant_day (participantId, day),
  INDEX idx_hourly_day_hour (day, hour),
  INDEX idx_hourly_participant_day_hour (participantId, day, hour),
  CONSTRAINT fk_hourly_participant FOREIGN KEY (participantId) REFERENCES participants(id),
  CONSTRAINT fk_hourly_device FOREIGN KEY (deviceId) REFERENCES devices(id),
  CONSTRAINT fk_hourly_workdir FOREIGN KEY (workdirId) REFERENCES workdirs(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS usage_sync_buckets_hourly (
  bucketKey VARCHAR(512) PRIMARY KEY,
  participantId VARCHAR(96) NOT NULL,
  deviceId VARCHAR(96) NOT NULL,
  day DATE NOT NULL,
  hour TINYINT NOT NULL,
  providerId VARCHAR(96) NOT NULL,
  granularity VARCHAR(16) NOT NULL DEFAULT 'hourly',
  bucketFingerprint VARCHAR(128) NOT NULL,
  rowCount INT NOT NULL,
  totalTokens BIGINT NOT NULL,
  clientGeneratedAt VARCHAR(40) NOT NULL,
  syncedAt VARCHAR(40) NOT NULL,
  updatedAt VARCHAR(40) NOT NULL,
  UNIQUE INDEX idx_sync_bucket_hourly_scope (participantId, deviceId, day, hour, providerId),
  INDEX idx_sync_bucket_hourly_participant_day (participantId, day)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
